// API
const DEFAULT_API = "/apis/v1";

// User
const USER_POSITION_PASSENGER = 0;
const USER_POSITION_DRIVER = 1;
const USER_STATUS_READY = 0;
const USER_STATUS_WORK = 1;

// Call
const CALL_STATUS_READY = 0;
const CALL_STATUS_APPROVE = 1;
const CALL_STATUS_REJECT = 2;
const CALL_STATUS_ARRIVE = 3;

// Common
const SERVER_RESULT_SUCCESS = 1;
const SERVER_RESULT_FAILURE = 0;

export {
  DEFAULT_API,
  USER_POSITION_PASSENGER,
  USER_POSITION_DRIVER,
  USER_STATUS_READY,
  USER_STATUS_WORK,
  CALL_STATUS_READY,
  CALL_STATUS_APPROVE,
  CALL_STATUS_REJECT,
  SERVER_RESULT_SUCCESS,
  SERVER_RESULT_FAILURE,
  CALL_STATUS_ARRIVE
};
