// User
const USER_POSITION_PASSENGER = 0;
const USER_POSITION_DRIVER = 1;
const USER_STATUS_READY = 0;
const USER_STATUS_WORK = 1;

// Call
const CALL_STATUS_READY = 0;
const CALL_STATUS_APPROVE = 1;
const CALL_STATUS_REJECT = 2;

const SERVER_RESULT_SUCCESS = 1;
const SERVER_RESULT_FAILURE = 0;

exports.USER_POSITION_PASSENGER = USER_POSITION_PASSENGER;
exports.USER_POSITION_DRIVER = USER_POSITION_DRIVER;
exports.USER_STATUS_READY = USER_STATUS_READY;
exports.USER_STATUS_WORK = USER_STATUS_WORK;
exports.CALL_STATUS_READY = CALL_STATUS_READY;
exports.CALL_STATUS_APPROVE = CALL_STATUS_APPROVE;
exports.CALL_STATUS_REJECT = CALL_STATUS_REJECT;
exports.SERVER_RESULT_SUCCESS = SERVER_RESULT_SUCCESS;
exports.SERVER_RESULT_FAILURE = SERVER_RESULT_FAILURE;
