FROM node:10.15.1

# RUN mkdir -p /home/ubuntu/backend
# WORKDIR /home/ubuntu/backend
# RUN mkdir -p /usr/src/app
# ADD . /usr/src/app
WORKDIR /usr/src/app
# COPY package*.json ./
# RUN npm install
# RUN npm i
EXPOSE 8081
# CMD ["ls", "/usr/src/app"]
# CMD ["npm", "start"]